name: Despliegue a Producción
on:
 push:
 branches: [ "main" ]
jobs:
 deploy:
 runs-on: ubuntu-latest
 environment: production
 steps:
 - name: Clonar repositorio
 uses: actions/checkout@v4
 - name: Instalar JDK 17 (Temurin)
 uses: actions/setup-java@v4
 with:
 distribution: temurin
 java-version: '17'
 - name: Compilar para Producción
 run: |
 mkdir -p out
 javac -d out src/*.java
 - name: Ejecutar aplicación en Producción
 run: java -cp out Main
